# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aboutme', '0001_initial_migration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='project name')),
                ('date_start', models.DateField(verbose_name='start date')),
                ('date_end', models.DateField(verbose_name='end date')),
                ('url', models.URLField(verbose_name='project url')),
                ('short_desc', models.CharField(max_length=128, verbose_name='short description')),
                ('description', models.TextField(verbose_name='description')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='aboutme.Profile')),
            ],
        ),
    ]
