"""
Django settings for jt_portfolio project.

Generated by 'django-admin startproject' using Django 1.10.5.
"""

from settings.base import *


DATABASES = {
    'default': {
        'ENGINE': dj_database_url.config(
            default=os.environ.get('DATABASE_URL')
        )
    }
}
