# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-07 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_init_model_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_type', models.CharField(max_length=16, verbose_name='skill type')),
                ('skill_name', models.CharField(max_length=16, verbose_name='skill name')),
                ('skill_description', models.TextField(verbose_name='skill description')),
                ('skill_strength', models.IntegerField(verbose_name='skill_strength')),
            ],
        ),
    ]
